### ISSUE TITLE
Error on example

### ISSUE THREAD

**Issue by xdougx** [werner/amatista#9]
When i tried to run the example:

``` crystal
require "amatista"

class HelloWorldController < Amatista::Controller
  get "/" do
    html = %(<h1> Hello World </h1>)
    respond_to(:html, html)
  end
end

class Main < Amatista::Base
  configure do |conf|
    conf[:secret_key] = "secret"
  end
end

app = Main.new

app.run 3000
```

Got this error

```
Undefined symbols for architecture x86_64:
  "_*Main::new:Main", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
  "_*Main@Amatista::Base#process_request<Main, HTTP::Request>:HTTP::Response", referenced from:
      _~fun_literal_26 in main.o
      _~fun_literal_26 in Main.o
  "_*Main@Amatista::Base#process_static<Main, String>:HTTP::Response?", referenced from:
      _~fun_literal_26 in main.o
      _~fun_literal_26 in Main.o
  "_*Main@Amatista::Base#run<Main, Int32>:Nil", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/douglas/workspace/crystal/importation/.crystal/crystal-run-app.tmp" "${@}"  -rdynamic  -lssl -lcrypto -levent -lpcl -lpcre -lgc -lpthread -ldl`
```

update:
Im using shard and the dependencies have been installed

```
$ crystal deps install
Updating https://github.com/werner/amatista.git
Updating https://github.com/spalger/crystal-mime.git
Installing amatista (0.4.1)
Installing mime (HEAD)
```

**Comment by werner** [comment]
Hi, what crystal version are you using?

**Comment by xdougx** [comment]
`Crystal 0.8.0 [e363b63] (Sat Sep 19 12:00:17 UTC 2015)`

**Comment by werner** [comment]
Did you try to remove the libs, .shards and .crystal folders?

**Comment by werner** [comment]
Hi, sorry for the late response, it looks like Amatista is not Osx compatible, I'll try to get a Mac and make some tests, meanwhile Amatista works only on linux.

**Comment by xdougx** [comment]
Okay :)

**Comment by werner** [comment]
Hi,

I did some tests in Yosemite, and everything seems to be working fine with crystal 0.9.0, could you please upgrade crystal and test it too, thanks.

**Comment by werner** [comment]
Closing this issue, if you have further problems, you can reopen this or create a new one.

Best regards.

**Comment by xdougx** [comment]
its was needed to change:
from: `require "mime"`
to `require "../../mime/mime"`
